name: dalgeurak_widget_package
description: A new Flutter project.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dimigoin_flutter_plugin: ^0.5.0

  get: ^4.6.5

  flutter_vibrate: ^1.3.0
  korea_regexp: ^0.1.0+1
  shared_preferences: ^2.0.8

  flutter_svg: ^0.23.0+1
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: lib/assets/fonts/Pretendard-Black.otf
          weight: 900
        - asset: lib/assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: lib/assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: lib/assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: lib/assets/fonts/Pretendard-Thin.otf
          weight: 100

